### ISSUE TITLE
Is there a way to add component to an existing Entity?

### ISSUE THREAD

**Issue by tomaszcekalo** [dartk/EntitiesDotNet#1]
See title. If I have an entity with components and at runtime want to add more components to it without destroying it and recreating -is there a way to do it?

**Comment by dartk** [comment]
I have added some methods to do that. Here is an example.

```c#
var manager = new EntityManager();
var entity = manager.CreateEntity(1, 12L, 12.3);
entity.RemoveComponents<long, double>();
entity.AddComponents("My entity");
```

But please do not use this library for anything. At it's current state it just serves educational purposes. It is a source generation experiment.

The API lacks features and is just bad. I have added those methods just for demonstration.
